### ISSUE TITLE
Course endpoint issues

### ISSUE THREAD

**Issue by JarneClauw** [SELab-2/UGent-3#182]
Issues found while testing the course endpoint.
This should fix all the tests. If something is meant to be like this, let me now.

```[tasklist]
### Tasks
- [x] (`test_get_courses_wrong_argument`) When given a wrong query argument, it should return a bad request and not just ignore it
- [x] (`test_post_courses_wrong_name_type`, `test_post_courses_wrong_ufora_id_type`, `test_patch_course_wrong_name_type`, `test_patch_course_wrong_ufora_id`, `test_patch_course_wrong_teacher_type`, `test_post_students_wrong_students_type`, `test_delete_students_wrong_students_type`) When posting or patching a course, we need to check if we got the right typing, otherwise return a bad request
- [x] (`tests_post_courses_incorrect_field`, `test_patch_course_incorrect_field`) When the data in posts and patches contain other fields than what is asked for, we should return a bad request.
- [x] (`test_patch_course_wrong_teacher`) We should check if the teacher exists instead of getting an internal server error.
- [x] (`test_post_students_wrong_students`, `test_delete_students_wrong_students`) After filtering the uids we will get an empty list, bad request.
- [x] (`test_post_admins_wrong_user`, `test_delete_admins_wrong_user`) 404 is the wrong status, it should be 400, the resource is available its the data that's wrong.
- [x] (`test_post_admins_correct`) If I'm correct something goes wrong in the query_agent
```
