### ISSUE TITLE
Cleanup code duplication in endpoints and create file for eacht endpoint seperately

### ISSUE THREAD

**Issue by AronBuzogany** [SELab-2/UGent-3#60]
```[tasklist]
### Tasks
- [ ] Create a utils file containing functions and modules that ought to be used by multiple endpoints
- [ ] Using the task above reduce code duplication in multiple endpoints
- [ ] Place every endpoint in seperate file 
```
